### ISSUE TITLE
Support endpoint DSL in YAML/JSON

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#366]
Instead of:

```
route:
  from:
    uri: telegram/bots?chatId=1234
  steps:
  - to:
      uri: knative:endpoint/sink
```

We may have (alternative):

```
route:
  from:
    telegram:
      type: bots
      chatId: 1234
  steps:
  - knative:
      type: endpoint
      name: sink
```

It's not only syntactic sugar, the most important part of the syntax below is that it's possible to define the **full json/yaml schema** of the endpoints, so that a web console or IDE can automatically suggest components and their properties and also completely validate the DSL.

There are tools for IDE that support URI validation, but they need a language server. This would be LSP free.

Maybe we can start moving the DSL to apache camel in order simplify impl.

**Comment by lburgazzoli** [comment]
For consistency should it be:

```yaml
route:
  telegram:
    type: bots
    chatId: 1234
  steps:
  - knative:
      type: endpoint
      name: sink
```

or do you think we should retain the `from` ?

**Comment by nicolaferraro** [comment]
Mmh.. that looks ok at first. What I fear is that after it's serialized and read again, we end up with this one, which is less clear:

```
route:
  steps:
  - knative:
      type: endpoint
      name: sink
  telegram:
    type: bots
    chatId: 1234
```
