### ISSUE TITLE
[yaml] support for configuring beans with the yaml dsl

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#376]
```yaml
- beans:
    - name: myBean
      type: com.acme.MyProcessor
      properties:
        field: value
-route:
  ...
```
