### ISSUE TITLE
Property substitution doesn't happen in from URI

### ISSUE THREAD

**Issue by igarashitm** [apache/camel-k-runtime#392]
I tried like this as a part of apache/camel-k-examples#12 and found that the property substitution doesn't happen for `salesforce.topic`
```yaml
    flow:
      from:
        uri: "salesforce:{{salesforce.topic}}"
```
It'd be nice to support it.
