### ISSUE TITLE
Fix kamelet entry in catalog

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#492]
```
    camel-kamelet:
      groupId: org.apache.camel.k
      artifactId: camel-kamelet
      schemes:
      - id: kamelet
        http: true
        passive: false
      dependencies:
      - groupId: org.apache.camel.k
        artifactId: camel-k-quarkus-kamelet
```

I think it should be marked as http=false, passive=true (like a passive endpoint, which has no effect on the trait processing). Then the operator will determine the actual type by looking at the kamelet code.
