### ISSUE TITLE
Failed to start Kamelet

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#493]
A simple kamelet:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: timer-source
  label:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Timer"
    description: "Produces periodic events with a custom payload"
    required:
      - message
    properties:
      period:
        title: Period
        description: The time interval between two events
        type: integer
        default: 1000
      message:
        title: Message
        description: The message to generate
        type: string
  types:
    out:
      mediaType: application/json
      schema:
        id: text.camel.apache.org
        type: string
  flow:
    from:
      uri: timer:tick
      parameters:
        period: "{{period}}"
      steps:
        - set-body:
            constant: "{{message}}"
        - to: "direct:{{routeId}}"

```

And a route:
```groovy
from('kamelet:timer-source?message=Camel+K')
    .log('${body}')

```

I'm getting:
```
[2] 2020-09-22 08:53:29,244 ERROR [io.qua.application] (main) Failed to start application (with profile prod): java.lang.RuntimeException: java.lang.RuntimeException: java.util.ConcurrentModificationException
[2]     at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:47)
[2]     at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
[2]     at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
[2]     at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:534)
[2]     at io.quarkus.runtime.Application.start(Application.java:90)
[2]     at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
[2]     at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
[2]     at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
[2]     at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
[2]     at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
[2] Caused by: java.lang.RuntimeException: java.util.ConcurrentModificationException
[2]     at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:65)
[2]     at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
[2]     ... 9 more
[2] Caused by: java.util.ConcurrentModificationException
[2]     at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
[2]     at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
[2]     at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:490)
[2]     at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:430)
[2]     at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:405)
[2]     at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:1185)
[2]     at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:93)
[2]     at org.apache.camel.main.BaseMainSupport.configureRoutes(BaseMainSupport.java:615)
[2]     at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:656)
[2]     at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:97)
[2]     at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:67)
[2]     at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
[2]     at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:118)
[2]     at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
[2]     ... 10 more
[2] 

```
