### ISSUE TITLE
Sink Kamelet not called

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k-runtime#500]
Trying this kamelet:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: echo-sink
  label:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "Echo"
    description: "Replies with an echo message to each incoming event"
    properties:
      prefix:
        title: Prefix
        description: The prefix to prepend to the incoming event
        type: string
        default: "echo: "
  types:
    in:
      mediaType: text/plain
    out:
      mediaType: text/plain
  flow:
    from:
      uri: "direct:#property:routeId"
      steps:
        - log: "Called Kamelet"
        - set-body:
            simple: "#property:prefix${body}"
```

Using that from an integratino like:

 ```groovy
from('timer:tick')
  .setBody().constant('Hello 2')
  .log("calling kamelet ...")
  .to("kamelet:echo-sink")
  .log('${body}')

```

From the logs, it does not seem the Kamelet to be called. It's printing "calling kamelet ...", then:

```
source-sink-5bc9b7d645-ts9ds integration 2020-09-23 10:04:57,679 WARN  [org.apa.cam.com.tim.TimerConsumer] (Camel (camel-1) thread #0 - timer://tick) Error processing exchange. Exchange[840B1B4EC9BE9A7-0000000000000006]. Caused by: [org.apache.camel.component.direct.DirectConsumerNotAvailableException - No consumers available on endpoint: direct://echo-sink-840B1B4EC9BE9A7-0000000000000000. Exchange[]]: org.apache.camel.component.direct.DirectConsumerNotAvailableException: No consumers available on endpoint: direct://echo-sink-840B1B4EC9BE9A7-0000000000000000. Exchange[]
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:59)
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.component.kamelet.KameletEndpoint$KameletProducer.process(KameletEndpoint.java:158)
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:169)
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:404)
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148)
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60)
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.processor.Pipeline.process(Pipeline.java:147)
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:287)
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:207)
source-sink-5bc9b7d645-ts9ds integration        at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76)
source-sink-5bc9b7d645-ts9ds integration        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
source-sink-5bc9b7d645-ts9ds integration        at java.base/java.util.TimerThread.run(Timer.java:506)

```
