### ISSUE TITLE
Support for simple, linear integration definitions

### ISSUE THREAD

**Issue by lburgazzoli** [apache/camel-k-runtime#659]
With the introduction of the [Kamelet EIP](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-16493?filter=allopenissues) in Camel, we could introduce a new way to define simple, linear integrations, like:

```yaml
steps:
  - kamelet: 
     name: foo
     properties:
       a: b  
  - kamelet:
     name: bar
     properties:
       c: d
```

This could be particular useful for the materialization of a KameletBinding to a real integration so the camel-k operator does not need to care about things such as proper placement of `from`, `to`, etc.
